---
version: "3"
services:
  # The main MyWordOfTheDay image
  mywordoftheday:
    image: simondrake/mywordoftheday:v1alpha1
    container_name: mywordoftheday
    depends_on:
      - mywordoftheday_db
    # Specify environment variables. The DB_* values should match
    # those in the mywordoftheday_db image
    environment:
      - SERVER_PORT=8080
      - HTTP_PROXY_ENABLED=true
      - HTTP_PROXY_PORT=8443
      - DB_HOST=mywordoftheday_db
      - DB_PORT=5432
      - DB_USERNAME=mywordoftheday
      - DB_PASSWORD=supersecretpassword
      - DB_NAME=mywordoftheday
      - SMTP_ENABLED=true
      - SMTP_SCHEDULE=0 12 * * *
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=yourgmailaddress@gmail.com
      - SMTP_PASSWORD=yourpassword # Note - if your gmail account uses 2FA you need to use an App Password - https://support.google.com/mail/answer/185833?hl=
      - SMTP_FROM_ADDRESS=yourgmailaddress@gmail.com
      - SMTP_TO_ADDRESSES=whoyouwanttosenditto@gmail.com
    # Optionally, provide a config file.
    # You don't need to speify this and the environment variables
    # volumes:
      # - ./config.yaml:/config/config.yaml
    ports:
      - 8443:8443
    restart: unless-stopped
  # The database for mywordoftheday
  mywordoftheday_db:
    image: postgres
    container_name: mywordoftheday_db
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_USER=mywordoftheday
      - POSTGRES_DB=mywordoftheday
    volumes:
      - ${HOME}/mywordoftheday/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  # Runs the Database migrations for mywordoftheday. For example, it ensures all
  # the required tables exist.
  mywordoftheday_migrations:
    image: simondrake/mywordoftheday_migrations:v1alpha1
    container_name: mywordoftheday_migrations
    depends_on:
      - mywordoftheday_db
    environment:
      - DATABASE_HOST=mywordoftheday_db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=mywordoftheday
      - DATABASE_PASSWORD=supersecretpassword
      - DATABASE_NAME=mywordoftheday
